// legacy/dynamic-components/migration-poster/src/yAxis.jsx
import React from 'react'

import { TICK_MARGIN_LEFT } from './config'

import { margin } from './config'

export const YAxis = ({ yScale, yTicks, yLabels, legendStyle, tickStyle }) => {
  return (
    <g {...legendStyle} transform={`translate(${TICK_MARGIN_LEFT}, 0)`}>
      {yLabels.map((tick, idx) => (
        <g key={`y-label-${idx}`} transform={`translate(0, ${yScale(tick)})`}>
          <text textAnchor='start'>
            <tspan dy='5' dx={-TICK_MARGIN_LEFT}>
              {tick}
            </tspan>
          </text>
        </g>
      ))}
      {yTicks.map((tick, idx) => (
        <g
          key={`y-tick-${idx}`}
          transform={`translate(${
            idx !== 0 && idx % 5 !== 0 ? margin.left - 6 : margin.left - 10
          }, ${yScale(tick)})`}
        >
          <line
            {...tickStyle}
            x1={
              idx !== 0 && idx % 5 !== 0 ? margin.left - 36 : margin.left - 32
            }
            x2={0}
          ></line>
        </g>
      ))}
    </g>
  )
}

// story-components/migration-poster/src/YAxis.svelte
<script lang="ts">
  import type { ScaleLinear } from "d3-scale";
  import { css } from "@story/theme/css";

  interface Props {
    yScale: ScaleLinear<number, number>;
    yLabels: number[];
    yTicks: number[];
    margin: { top: number; bottom: number; left: number; right: number };
  }

  let { yScale, yLabels, yTicks, margin }: Props = $props();
  const TICK_MARGIN_LEFT = 9;
</script>

<g transform={`translate(${TICK_MARGIN_LEFT}, 0)`}
   class={css({ fontSize: "14px", fontFamily: "gtAmericaStandard", fill: "text" })}>
  {#each yLabels as tick (tick)}
    <g transform={`translate(0, ${yScale(tick)})`}>
      <text text-anchor="start">
        <tspan dy="5" dx={-TICK_MARGIN_LEFT}>{tick}</tspan>
      </text>
    </g>
  {/each}
  {#each yTicks as tick, idx (tick)}
    {@const major = idx === 0 || idx % 5 === 0}
    <g transform={`translate(${major ? margin.left - 10 : margin.left - 6}, ${yScale(tick)})`}>
      <line
        x1={major ? margin.left - 32 : margin.left - 36}
        x2={0}
        class={css({ stroke: "text", strokeWidth: "1px", opacity: "0.5", shapeRendering: "crispEdges" })} />
    </g>
  {/each}
</g>
